## parameter setup




## Enable
# focal: 1:YES 0:NO
CAM_MANUAL_FOCAL_EN = 1
CAM_BUFFERSIZE_EN = 0
CAM_AUTO_FOCAL_EN = 0
CAM_AUTO_WB_EN = 0
# test mode (0: in-plane, 1:out-of-plane)
TEST_MODE_EN = 0
TEST_ROTATE_IMG_EN = 1
TEST_REC_IMG_EN = 1
TEST_IMG_DIR = 'Target'
TEST_POINT_ARRAY = 25
TEST_INTERVAL = 10
TEST_SUBSET_SIZE_1B2B = 31
TEST_SUBSET_SIZE_1B1A = 31
TEST_SUBSET_SIZE_2B2A = 31

TEST_SCAN_SIZE_1B2B = 31
TEST_SCAN_SIZE_1B1A = 31
TEST_SCAN_SIZE_2B2A = 31

#TEST_SHIFT = 
TEST_GAUSSIANBLUR_EN = 0




## camera parameters
# focal
CAM1_FOCAL = 70
CAM2_FOCAL = 70
# camera index
CAM1_ID = 1
CAM2_ID = 0

## camera calibration
CAL_CHESSBOARD_SIZE = (9,6)
CAL_IMAGE_RES = (640,480)

CAL_ITERATION_TIMES = 100
CAL_ACCURACY = 0.0001

CAL_SQUARE_SIZE = 8 # unit: mm

## TEST SETTING
TEST_LOAD = 5


